name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the workflow will run
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrforfastapi.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}  # Azure username or service principal username
        password: ${{ secrets.ACR_PASSWORD }}  # Azure password or service principal password or ACR Access Key

    - name: Build Docker image
      run: |
        docker build -t acrforfastapi.azurecr.io/trial-image:${{ github.sha }} -t acrforfastapi.azurecr.io/trial-image:latest .
        # Use the commit SHA as a tag

    - name: Push Docker image to ACR
      run: |
        docker push acrforfastapi.azurecr.io/trial-image:${{ github.sha }} -t acrforfastapi.azurecr.io/trial-image:latest .
        # Push the newly built image to Azure Container Registry

